INSERT INTO movie
(title, release_year, duration, rating, poster_url, synopsis, genre_id) VALUES
-- ACCIÓN (id 1)
('Mad Max: Fury Road',            2015, 120, 8.1, 'https://…/furyroad.jpg',
 'Caos motorizado en un desierto post-apocalíptico.', 1),
('John Wick',                     2014, 101, 7.9, 'https://…/johnwick.jpg',
 'Un ex-asesino a sueldo desata su venganza.', 1),
('Gladiator',                     2000, 155, 8.5, 'https://…/gladiator.jpg',
 'Un general romano convertido en esclavo lucha por su libertad.', 1),
('Die Hard',                      1988, 132, 8.2, 'https://…/diehard.jpg',
 'Un policía de Nueva York contra terroristas en Nochebuena.', 1),
('Casino Royale',                 2006, 144, 8.0, 'https://…/casinoroyale.jpg',
 'Los orígenes de James Bond en su primera misión 00.', 1),
('The Dark Knight',               2008, 152, 9.0, 'https://…/darkknight.jpg',
 'Batman enfrenta al Joker por el alma de Gotham.', 1),
('Inglourious Basterds',          2009, 153, 8.3, 'https://…/basterds.jpg',
 'Comando aliado planea asesinar a líderes nazis.', 1),
('Skyfall',                       2012, 143, 7.8, 'https://…/skyfall.jpg',
 'El pasado de M pone a MI6 contra las cuerdas.', 1),

-- COMEDIA (id 2)
('The Grand Budapest Hotel',      2014, 100, 8.1, 'https://…/gbhotel.jpg',
 'Las aventuras del conserje de un lujoso hotel europeo.', 2),
('Superbad',                      2007, 113, 7.6, 'https://…/superbad.jpg',
 'Dos amigos intentan conseguir alcohol para la última fiesta.', 2),
('Groundhog Day',                 1993, 101, 8.1, 'https://…/groundhog.jpg',
 'Un meteorólogo revive el mismo día una y otra vez.', 2),
('The Hangover',                  2009, 100, 7.7, 'https://…/hangover.jpg',
 'Despiertan en Las Vegas sin recordar nada de la despedida.', 2),
('Jojo Rabbit',                   2019, 108, 7.9, 'https://…/jojo.jpg',
 'Un niño alemán cuyos héroes cambian durante la Segunda Guerra.', 2),
('Paddington 2',                  2017, 103, 7.8, 'https://…/paddington2.jpg',
 'El oso más querido de Londres en una nueva aventura.', 2),

-- DRAMA (id 3)
('The Shawshank Redemption',      1994, 142, 9.3, 'https://…/shawshank.jpg',
 'Esperanza y amistad tras los muros de una prisión.', 3),
('Forrest Gump',                  1994, 142, 8.8, 'https://…/forrest.jpg',
 'Un hombre extraordinario en momentos clave de la historia EE. UU.', 3),
('Fight Club',                    1999, 139, 8.8, 'https://…/fightclub.jpg',
 'Un insomne y un vendedor de jabón fundan un club secreto.', 3),
('Parasite',                      2019, 132, 8.5, 'https://…/parasite.jpg',
 'Dos familias de mundos opuestos colisionan.', 3),
('La La Land',                    2016, 128, 8.0, 'https://…/lalaland.jpg',
 'Sueños y amor en Los Ángeles al ritmo del jazz.', 3),
('Whiplash',                      2014, 106, 8.5, 'https://…/whiplash.jpg',
 'Un joven baterista y su exigente profesor de música.', 3),
('The Godfather',                 1972, 175, 9.2, 'https://…/godfather.jpg',
 'El ascenso de Michael Corleone en la mafia.', 3),
('A Beautiful Mind',              2001, 135, 8.2, 'https://…/beautifulmind.jpg',
 'La vida del matemático John Nash y su lucha contra la esquizofrenia.', 3),
('Nomadland',                     2020, 108, 7.4, 'https://…/nomadland.jpg',
 'Una mujer recorre EE. UU. como nómada moderna.', 3),

-- CIENCIA FICCIÓN (id 4)
('Blade Runner 2049',             2017, 164, 8.0, 'https://…/br2049.jpg',
 'Un blade runner descubre un secreto que podría sumir a la sociedad en el caos.', 4),
('Inception',                     2010, 148, 8.8, 'https://…/inception.jpg',
 'El arte de robar secretos a través de los sueños.', 4),
('Arrival',                       2016, 116, 7.9, 'https://…/arrival.jpg',
 'Lingüista intenta comunicarse con extraterrestres.', 4),
('Ex Machina',                    2014, 108, 7.7, 'https://…/exmachina.jpg',
 'Programador evalúa la consciencia de una IA humanoide.', 4),
('Her',                           2013, 126, 8.0, 'https://…/her.jpg',
 'Un hombre se enamora de un sistema operativo.', 4),
('Dune: Part One',                2021, 155, 8.0, 'https://…/dune2021.jpg',
 'El joven Paul Atreides y la lucha por Arrakis.', 4),
('Alien',                         1979, 117, 8.5, 'https://…/alien.jpg',
 'Terror en el espacio profundo.', 4),

-- ANIMACIÓN (id 5)
('Spirited Away',                 2001, 125, 8.6, 'https://…/spiritedaway.jpg',
 'Chihiro entra en un mundo de espíritus y dioses antiguos.', 5),
('Up',                            2009, 96,  8.3, 'https://…/up.jpg',
 'Un anciano viaja a Cataratas del Paraíso en su casa voladora.', 5),
('Coco',                          2017, 105, 8.4, 'https://…/coco.jpg',
 'Un niño mexicano cruza al Mundo de los Muertos.', 5),
('Inside Out',                    2015, 95,  8.1, 'https://…/insideout.jpg',
 'Las emociones de Riley cobran vida propia.', 5),
('The Lion King',                 1994, 88,  8.5, 'https://…/lionking.jpg',
 'El destino de Simba en las Tierras del Reino.', 5),
('Ratatouille',                   2007, 111, 8.1, 'https://…/ratatouille.jpg',
 'Una rata con talento culinario en París.', 5),
('How to Train Your Dragon',      2010, 98,  8.1, 'https://…/httyd.jpg',
 'Vikingo entabla amistad con un dragón.', 5),
('Shrek',                         2001, 90,  7.9, 'https://…/shrek.jpg',
 'Un ogro se embarca en una misión para rescatar a la princesa.', 5),
('The Incredibles',               2004, 115, 8.0, 'https://…/incredibles.jpg',
 'Familia de superhéroes vuelve a la acción.', 5),
('Kubo and the Two Strings',      2016, 102, 7.8, 'https://…/kubo.jpg',
 'Aventura épica en stop-motion inspirada en el folclore japonés.', 5);
