version: "3.9"

services:
  db:
    image: mysql:8.3
    container_name: copilot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: copflix
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d